### ISSUE TITLE
supporting PCF 2.0

### ISSUE THREAD

**Issue by HoffiMuc** [Azure/oms-log-analytics-firehose-nozzle#10]
will this nozzle be "officially" compatible for PCF 2.0 (meaning be downloadable as "depends on PCF 2.0.x" any time soon?

**Comment by HDYA** [comment]
If you check the tile on Pivotal Network, you will find that we have already "officially" declare support for PCF 2.0.
Sorry, but actually I didn't quite follow your question. I believe that we shouldn't set it to depend on PCF 2.0.x, in order not to terminate support for PCF 1.12.x.

**Comment by HDYA** [comment]
Close due to inactivity.

**Comment by HDYA** [comment]
Close due to inactivity.
