### ISSUE TITLE
Re-generate nozzle tile to use xenial stemcell

### ISSUE THREAD

**Issue by bingosummer** [Azure/oms-log-analytics-firehose-nozzle#14]

**Comment by ntdt** [comment]
It'd be nice to have the tile with xenial. We are considering using this tile with PCF 2.3.

**Comment by HDYA** [comment]
We will release a new version to support Xenial Stemcell very soon, thanks.

**Comment by HDYA** [comment]
Version 1.4.0 has been released, closing this issue.
https://network.pivotal.io/products/microsoft-azure-log-analytics-nozzle/
