### ISSUE TITLE
Failed to compile due to no support for Go 1.10.0 in the go_buildpack

### ISSUE THREAD

**Issue by austinbv** [Azure/oms-log-analytics-firehose-nozzle#23]
Hey all it looks like the go version needs to be updated as the build pack no longer supports go 1.10.0.

I am installing the nozzle as a tile in ops-manager on Pivotal Cloud Foundry. Here are the relevant logs. 

```
             2019-08-20T05:10:20.86+0000 [STG/0] OUT -----&gt; Installing dep 0.5.4  
             2019-08-20T05:10:20.86+0000 [STG/0] OUT        Copy [/tmp/buildpacks/52a307ca94edfbb724794d48ed1a7c48/dependencies/f1900fcb2de60a12ea6743ecf05e14d2/dep-v0.5.4-linux-x64-cflinuxfs3-79b3ab9e.tgz]  
             2019-08-20T05:10:21.10+0000 [STG/0] OUT        [31;1m**ERROR**[0m Unable to determine Go version to install: no match found for 1.10.x in [1.11.11 1.11.12 1.12.6 1.12.7]  
             2019-08-20T05:10:21.11+0000 [STG/0] ERR Failed to compile droplet: Failed to run all supply scripts: exit status 16  
```

**Comment by HDYA** [comment]
Hi @austinbv , thanks for reporting this issue, we've been working on this and will release fixes soon. Thanks.

**Comment by bgandon** [comment]
We are encountering this issue in our production Concourse pipeline, which has recently bumped the Go Buildpack of our sandbox Cloud Foundry foundation, from v1.8.40 (still supporting Golang v1.10.x) to v1.8.42 (no more supporting Golang v1.10.x).

As a temporary fix, we plan to rename the bumped buildpack with `cf rename-buildpack` and then do a `cf create-buildpack` to recreate the `go_buildback` to its former version v1.8.40.

**Comment by skertz** [comment]
Ran into this same thing while updating to PCF 2.5 which came with 1.8.42. We too invoke a work-around. Keep in mind that the latest buildpack (yesterday) just removed Go 1.11 - supports 1.12/1.13
Maybe take a larger leap forward when updating the nozzle.

**Comment by kr-jmd** [comment]
I am running into the same bug with the latest version (1.4.2). Running OpsMan/PAS 2.7 on Azure and getting an error trying to get to github to get the GoPack...obviously because the vm cannot access the internet. Is there a way to change this so that it uses cached buildpack in PCF?

**Comment by bgandon** [comment]
For us, this has been fixed with a more recent version of the Nozzle.
We can fix this issue. Thank you for your support.

**Comment by HDYA** [comment]
Version 1.4.2 should have fixed this issue, closing it
