### ISSUE TITLE
Any plan to support pcf 1.12?

### ISSUE THREAD

**Issue by kamoljan** [Azure/oms-log-analytics-firehose-nozzle#4]

**Comment by HDYA** [comment]
Hi @kamoljan . We haven't tested it on PCF 1.12 yet. We will test it shortly after we upgrade our dev env but you can try to use it under PCF 1.12 now. It should work fine and feel free to contact us if there is any problems. Thanks.

**Comment by kamoljan** [comment]
@HDYA thank you for your prompt response. 
btw, how about stemcell?

**Comment by HDYA** [comment]
@kamoljan  We're using bosh-stemcell-3445.11-azure-hyperv-ubuntu-trusty-go_agent for now, but it should work fine with all versions which support GoLang 1.7 or 1.9. It's not guaranteed though since we didn't have time to test all stemcell versions yet.

**Comment by kamoljan** [comment]
ic.. thank you @HDYA !
