### ISSUE TITLE
App log Filtering by Orgs or/and Spaces

### ISSUE THREAD

**Issue by ScottGuymer** [Azure/oms-log-analytics-firehose-nozzle#7]
We have a CF installation that is used by many teams, we would only want to ship the logs for the apps we care about into OMS. Is it possible to do some filtering by space or app?

**Comment by HDYA** [comment]
Hi @ScottGuymer

Sorry for the late response, for now the nozzle only support Event Filter, which filter logs by event like HTTP or METRIC. 
I'll investigate it a bit deeper but for now, I would recommend you to perform filtering in OMS. 

Wish you all the best.

**Comment by HDYA** [comment]
Hi @ScottGuymer ,

Thanks for raising this valuable suggestion, we'll add the feature to future versions.
I'll get back to this issue whenever there is further information available.

Wish you all the best.

**Comment by HDYA** [comment]
Hi @ScottGuymer ,

This feature has been merged into master branch, feel free to contact us if there is any further problems.
If you want to try this feature with tile in Ops Manager, you might have to wait for our next release around this December.

Thanks
